'use client'
import "./globals.css";
import { SidebarProvider, useSidebarContext } from "@/lib/context/SidebarContext";
import { Flowbite } from "flowbite-react";
import  Navbar from './components/layout/navbar/Navbar'
import Sidebar from './components/layout/sidebar/Sidebar'
import classNames from "classnames";
import theme from '../lib/helpers/flowbiteTheme'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {isOpenOnSmallScreens} = useSidebarContext()

  return (
    <html lang="en">
      <body className="bg-gray-900 antialiased min-h-screen">
        <Flowbite theme={{ theme }}>
          <SidebarProvider>
            <Navbar />
            <div className="flex items-start pt-16">
              <Sidebar />
              <main
                className={classNames(
                  "overflow-y-auto relative w-full h-full bg-gray-900",
                  isOpenOnSmallScreens ? "lg:ml-16" : "lg:ml-64"
                )}
              >
                {children}
              </main>
            </div>
          </SidebarProvider>
        </Flowbite>
      </body>
    </html>
  );
}