'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, useSidebarContext } from "@/lib/context/SidebarContext";
import { Flowbite, useThemeMode } from "flowbite-react";
import Navbar from '../ui/navbar/Navbar'
import Sidebar from '../ui/sidebar/Sidebar'
import classNames from "classnames";
import theme from '../lib/helpers/flowbiteTheme'
import { FC, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {isOpenOnSmallScreens} = useSidebarContext()
  const dark = localStorage.getItem("theme") === "dark";

  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="bg-gray-50 dark:bg-gray-900 antialiased">
        <Flowbite theme={{ dark, theme }}>
          <PersistFlowbiteThemeToLocalStorage />
          <SidebarProvider>
            <Navbar />
            <div className="flex items-start pt-16">
              <Sidebar />
              <main
              className={classNames(
                "overflow-y-auto relative w-full h-full bg-gray-50 dark:bg-gray-900",
                isOpenOnSmallScreens ? "lg:ml-16" : "lg:ml-64"
              )}
            >
              {children}
            </main>
            </div>
          </SidebarProvider>
        </Flowbite>
      </body>
    </html>
  );
}

const PersistFlowbiteThemeToLocalStorage: FC = () => {
  const [themeMode] = useThemeMode();

  useEffect(() => {
    localStorage.setItem("theme", themeMode);
  }, [themeMode]);

  return <></>;
};
